import subprocess
import os
import sys
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))


def analyze_repo(files_found, file_contents):
    prompt = f"""
You are a developer tool that analyzes GitHub repositories.

I cloned a repository and found these files:
{files_found}

Here are the contents of the config files I found:
{file_contents}

Your job is to help someone run this project locally.

Strict rules you must follow:
- For Node.js projects that have package.json:
  - If yarn.lock exists, INSTALL_COMMAND must be: yarn install
  - Otherwise INSTALL_COMMAND must be: npm install
- For Python projects that have requirements.txt, INSTALL_COMMAND must be: pip3 install -r requirements.txt
- For Python projects that have poetry.lock, INSTALL_COMMAND must be: poetry install
- For Python projects that have setup.py, INSTALL_COMMAND must be: pip3 install -e .
- For Python projects that have pyproject.toml only, INSTALL_COMMAND must be: pip3 install .
- If none of these files exist, INSTALL_COMMAND is NONE
- START_COMMAND should be the exact command to run the project
- If no start command exists, write NONE
- ENV_VARS should list required environment variable names separated by commas, or NONE
- Never mix Node.js and Python commands

You must respond in this EXACT format, no extra text, no explanation:

PROJECT_TYPE: <type here>
INSTALL_COMMAND: <exact command or NONE>
START_COMMAND: <exact command or NONE>
ENV_VARS: <comma separated list or NONE>
"""
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content


def parse_response(ai_response):
    parsed = {}
    for line in ai_response.strip().split("\n"):
        if ":" in line:
            key, value = line.split(":", 1)
            parsed[key.strip()] = value.strip()
    return parsed


def validate_parsed(parsed, files_found):

    # Override AI if install command is clearly wrong
    if "package.json" in files_found and "yarn.lock" not in files_found:
        if parsed.get("INSTALL_COMMAND") not in ["npm install", "yarn install"]:
            print("  AI gave wrong install command, using npm install instead")
            parsed["INSTALL_COMMAND"] = "npm install"

    if "yarn.lock" in files_found:
        parsed["INSTALL_COMMAND"] = "yarn install"

    if "requirements.txt" in files_found and "package.json" not in files_found:
        if "pip" not in parsed.get("INSTALL_COMMAND", ""):
            print("  AI gave wrong install command, using pip3 install -r requirements.txt instead")
            parsed["INSTALL_COMMAND"] = "pip3 install -r requirements.txt"

    if "poetry.lock" in files_found:
        parsed["INSTALL_COMMAND"] = "poetry install"

    # Fill missing keys with defaults
    if "INSTALL_COMMAND" not in parsed:
        parsed["INSTALL_COMMAND"] = "NONE"

    if "START_COMMAND" not in parsed:
        parsed["START_COMMAND"] = "NONE"

    if "ENV_VARS" not in parsed:
        parsed["ENV_VARS"] = "NONE"

    if "PROJECT_TYPE" not in parsed:
        parsed["PROJECT_TYPE"] = "Unknown"

    return parsed


def create_env_file(folder_name, env_vars):
    if env_vars == "NONE" or not env_vars:
        return

    env_path = os.path.join(folder_name, ".env")

    if os.path.exists(env_path):
        print("\n.env file already exists, skipping")
        return

    variables = [v.strip() for v in env_vars.split(",")]

    with open(env_path, "w") as f:
        f.write("# Auto-generated by devrun\n")
        f.write("# Fill in the values below\n\n")
        for var in variables:
            f.write(f"{var}=\n")

    print(f"\nCreated .env file with {len(variables)} variables:")
    for var in variables:
        print(f"  {var}=")
    print("Fill in the values before starting the project")

def update_devrun():
    devrun_dir = os.path.expanduser("~/Desktop/devrun")
    print(f"Looking in: {devrun_dir}")
    print(f"Exists: {os.path.exists(devrun_dir)}")
    print(f"Has .git: {os.path.exists(os.path.join(devrun_dir, '.git'))}")

    
def update_devrun():
    print("\nUpdating devrun...")

    devrun_dir = os.path.expanduser("~/Desktop/devrun")

    result = subprocess.run(
        ["git", "pull"],
        cwd=devrun_dir,
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        print("Update failed:")
        print(result.stderr)
        exit()

    print(result.stdout.strip())

    print("Reinstalling...")
    result = subprocess.run(
        ["pip3", "install", "-e", "."],
        cwd=devrun_dir,
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        print("devrun updated successfully")
    else:
        print("Reinstall failed:")
        print(result.stderr)


def main():
    if len(sys.argv) < 2:
        print("Usage: devrun <github_repo_url>")
        print("       devrun --update")
        exit()

    if sys.argv[1] == "--update":
        update_devrun()
        exit()

    repo_url = sys.argv[1]
    folder_name = repo_url.split("/")[-1]

    # Step 1: Clone repo
    if not os.path.exists(folder_name):
        print(f"\nCloning {repo_url}...")
        result = subprocess.run(
            ["git", "clone", repo_url],
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            print("Clone successful")
        else:
            print("Clone failed:")
            print(result.stderr)
            exit()
    else:
        print(f"\nFolder '{folder_name}' already exists, skipping clone")

    # Step 2: Read config files
    files_found = []
    file_contents = {}

    if os.path.exists(folder_name):
        files_found = os.listdir(folder_name)

        config_files = [
            "package.json", "requirements.txt", "Dockerfile",
            ".env.example", "README.md", "setup.py",
            "pyproject.toml", "yarn.lock", "poetry.lock"
        ]

        for config in config_files:
            full_path = os.path.join(folder_name, config)
            if os.path.exists(full_path):
                with open(full_path, "r") as f:
                    file_contents[config] = f.read()

    # Step 3: Ask AI to analyze
    print("\nAnalyzing repo...")
    ai_response = analyze_repo(files_found, file_contents)

    # Step 4: Parse and validate response
    parsed = parse_response(ai_response)
    parsed = validate_parsed(parsed, files_found)

    # Retry once if parsing failed
    if not parsed or "INSTALL_COMMAND" not in parsed:
        print("AI response unclear, retrying...")
        ai_response = analyze_repo(files_found, file_contents)
        parsed = parse_response(ai_response)
        parsed = validate_parsed(parsed, files_found)

    if not parsed:
        print("\nCould not analyze this repo automatically.")
        print(f"Try setting it up manually inside ./{folder_name}")
        exit()

    # Step 5: Execute install command
    install_cmd = parsed.get("INSTALL_COMMAND", "NONE")

    if install_cmd != "NONE":
        print(f"\nRunning: {install_cmd}")
        cmd_parts = install_cmd.split()

        process = subprocess.Popen(
            cmd_parts,
            cwd=folder_name,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True
        )

        for line in process.stdout:
            print(f"  {line}", end="")

        process.wait()

        if process.returncode == 0:
            print("\nInstall successful")
        else:
            print("\nInstall failed. Common fixes:")
            if "npm" in install_cmd:
                print("  - Make sure Node.js is installed: https://nodejs.org")
                print("  - Try running manually: cd", folder_name, "&&", install_cmd)
            elif "pip" in install_cmd:
                print("  - Make sure Python is installed: https://python.org")
                print("  - Try running manually: cd", folder_name, "&&", install_cmd)
            exit()
    else:
        print("\nNo install command needed")

    # Step 6: Create .env file if needed
    env_vars = parsed.get("ENV_VARS", "NONE")
    create_env_file(folder_name, env_vars)

    # Step 7: Final summary
    start_cmd = parsed.get("START_COMMAND", "NONE")

    print("\n" + "="*40)
    print("DEVRUN COMPLETE")
    print("="*40)
    print(f"Project Type : {parsed.get('PROJECT_TYPE', 'Unknown')}")
    print(f"Location     : ./{folder_name}")

    if install_cmd != "NONE":
        print(f"Dependencies : Installed")

    if env_vars != "NONE":
        print(f"Env Vars     : Check .env file in ./{folder_name}")

    if start_cmd != "NONE":
        print(f"\nTo start the project:")
        print(f"  cd {folder_name} && {start_cmd}")
    else:
        print(f"\nNo start command detected")
        print(f"Check the README inside ./{folder_name} for instructions")

    print("="*40)


if __name__ == "__main__":
    main()